/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import model.Jatekos;
import model.Tabla;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    private JToggleButton[] gombok;
    private Jatekos j1;
    private Jatekos j2;
    private Jatekos aktJatekos;
    private int sor;
    private int oszlop;
    private String eredmeny = "";
    private boolean vege = false;
    private Tabla tabla;

    public Foablak() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tizes Amőba");
        tabla = new Tabla();
        j1 = new Jatekos("Béla", "X");
        j2 = new Jatekos("Erika", "O");

        aktJatekos = j1;

        gombok = new JToggleButton[100];

        for (int i = 0; i < gombok.length; i++) {
            int index = i;
            gombok[i] = new JToggleButton("");//ez lesz beleírva a gombokba
            gombok[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JToggleButton gomb = (JToggleButton) e.getSource();
                    gomb.setEnabled(false);//Jó helyen van???
                    lepesFeldolgoz(index, gomb);
 
                }
            });
            pnlGombok.add(gombok[i]);
        }

        pack();//ez állítja a méreteket, ez a JFramenek egy metódusa
    }

    public void lepesFeldolgoz(int index, JToggleButton gomb) {

        if (gomb.isSelected()) {
            gomb.setText(aktJatekos.getJel());
            //System.out.println(index);
            sor = index / 10;
            System.out.println("Sor: " + sor);
            oszlop = index % 10;
            System.out.println("Oszlop: " + oszlop);
            tabla.lepes(sor, oszlop, aktJatekos);
            eredmeny = tabla.nyertesVizsgal(aktJatekos, sor, oszlop);
            System.out.println(eredmeny);

            eredmenyVizsgal(index, gomb);

            //aktJatekos csere
            if (aktJatekos == j1) {
                aktJatekos = j2;
            } else if (aktJatekos == j2) {
                aktJatekos = j1;
            }
        }
    }

    public void eredmenyVizsgal(int index, JToggleButton gomb) {
        if (eredmeny.equals("Döntetlen") || eredmeny.contains(" nyert")) {
            vege = true;
            JOptionPane.showMessageDialog(rootPane, aktJatekos.getJel() + " nyert", "Játék vége",
                    JOptionPane.INFORMATION_MESSAGE);
            Object[] valaszok = {"Igen", "Nem"};
            int valasz = JOptionPane.showOptionDialog(this, "Szeretnéd úrja kezdeni a játákot?", "Újra?",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, valaszok, valaszok[0]);
            if (valasz == JOptionPane.YES_OPTION) {
                for (int i = 0; i < gombok.length; i++) {
                    gombok[i].setSelected(false);
                    gombok[i].setEnabled(true);
                    gombok[i].setText("");
                    //System.out.println(gombok[i].getText());
                }
                tabla = new Tabla();
                aktJatekos = j1;
                lepesFeldolgoz(index, gomb);

            } else {
                System.exit(0);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGombok = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGombok.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pnlGombok.setLayout(new java.awt.GridLayout(10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGombok, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGombok, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlGombok;
    // End of variables declaration//GEN-END:variables
}
